services:
  postgres:
    image: "postgres:17.5-alpine"
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=test"

  projects:
    build:
      dockerfile: "./docker/Dockerfile.${MOD:-dev}"
    environment:
      - "PROJECTS__API__HOST=0.0.0.0"
      - "PROJECTS__API__PORT=80"
      - "PROJECTS__API__HEADER_FOR_ACCOUNT_ID=x-account-id"
      - "PROJECTS__GENERAL__PLANS_LIMIT=20"
      - "PROJECTS__GENERAL__PROJECTS_LIMIT=20"
      - "PROJECTS__POSTGRES__HOST=postgres"
      - "PROJECTS__POSTGRES__PORT=5432"
      - "PROJECTS__POSTGRES__USER=test"
      - "PROJECTS__POSTGRES__PASSWORD=test"
      - "PROJECTS__POSTGRES__DB=test"
      - "PROJECTS__LOGGING__LEVEL=INFO"
    ports:
      - "127.0.0.1:${PORT:-8080}:80"

networks:
  default:
    driver: "bridge"
