FROM ghcr.io/astral-sh/uv:python3.12-alpine AS base
WORKDIR /service
COPY pyproject.toml uv.lock ./
RUN uv sync --no-dev --locked

FROM base AS dev
WORKDIR /service
COPY ./app ./app
CMD ["uv", "run", "python", "-m", "app.main"]