FROM ghcr.io/astral-sh/uv:python3.12-trixie AS base
WORKDIR /service
COPY pyproject.toml uv.lock ./
RUN uv sync --no-dev --locked

FROM base
WORKDIR /service
COPY ./app ./app
COPY Makefile .
ENV PATH="/service/.venv/bin:$PATH"
CMD ["make", "local"]
