local:
	npm run dev

up:
	docker compose -f docker-compose.yml up --build

down:
	docker compose -f docker-compose.yml down

test:
	npm run test

coverage:
	npm run coverage

format:
	npm run format

format-check:
	npm run format:check
