events {
}

http {
    upstream projects {
        server projects:80;
    }
    upstream exporter {
        server exporter:80;
    }
    upstream generator {
        server generator:80;
    }
    upstream catalog {
        server catalog:80;
    }
    upstream auth {
        server auth:80;
    }
    upstream minio {
        server minio:9000;
    }
    upstream assets {
        server assets:80;
    }
    upstream frontend {
        server frontend:80;
    }

    server {
        listen 80;

        # Catalog service.
        location /api/catalog {
            proxy_pass http://catalog;
            rewrite ^/api/catalog(/.*)?$ $1 break;
        }

        # Exporter service.
        location ~ ^/api/projects/([0-9A-Za-z\-]+)/export/pdf$ {
            proxy_pass http://exporter;
            rewrite ^/api(/.*)?$ $1 break;
        }
        location ~ ^/api/plans/([0-9A-Za-z\-]+)/export/dxf$ {
            proxy_pass http://exporter;
            rewrite ^/api(/.*)?$ $1 break;
        }

        # Projects service.
        location = /api/projects {
            proxy_pass http://projects;
            rewrite ^/api(/.*)?$ $1 break;
        }
        location ~ ^/api/projects/([0-9A-Za-z\-])+(/publish|/unpublish|/plans)?$ {
            proxy_pass http://projects;
            rewrite ^/api(/.*)?$ $1 break;
        }
        location ~ ^/api/plans/([0-9A-Za-z\-]+)$ {
            proxy_pass http://projects;
            rewrite ^/api(/.*)?$ $1 break;
        }

        # Generator service.
        location ~ ^/api/projects/([0-9A-Za-z\-])+/prompts$ {
            proxy_pass http://generator;
            rewrite ^/api(/.*)?$ $1 break;
        }
    }
}